const GENERAL_QUOTES_AR = [
  { q: 'النجاح ليس النهاية، والفشل ليس قاتلاً: الشجاعة لمواصلة الطريق هي ما يهم.', by: 'وينستون تشرشل' },
  { q: 'الطريقة الوحيدة لعمل أشياء عظيمة هي أن تحب ما تفعله.', by: 'ستيف جوبز' },
  { q: 'لا تخف من التنازل عن الجيد من أجل العظيم.', by: 'جون روكفلر' },
  { q: 'التعليم هو أقوى سلاح يمكنك استخدامه لتغيير العالم.', by: 'نيلسون مانديلا' },
  { q: 'السر في المضي قدماً هو البدء.', by: 'مارك توين' },
  { q: 'صدق أنك تستطيع، وستكون في منتصف الطريق.', by: 'ثيودور روزفلت' },
  { q: 'لا تتوقف عندما تتعب، توقف عندما تنتهي.', by: 'مارلين مونرو' },
  { q: 'الأشياء العظيمة لا تأتي من مناطق الراحة.', by: 'نيل آرمسترونغ' },
  { q: 'كل خبير كان يوماً مبتدئاً.', by: 'هيلين هايز' },
  { q: 'المستقبل يعتمد على ما تفعله اليوم.', by: 'مهاتما غاندي' },
  { q: 'ليس المهم مدى بطئك طالما أنك لا تتوقف.', by: 'كونفوشيوس' },
  { q: 'الاستثمار في المعرفة يدفع أفضل الفوائد.', by: 'بنجامين فرانكلين' },
  { q: 'قطرة المطر تحفر في الصخر، ليس بالعنف ولكن بالتكرار.', by: 'لوكريتيوس' },
  { q: 'أكبر ضعف لنا يكمن في الاستسلام. أضمن طريقة للنجاح هي المحاولة مرة أخرى.', by: 'توماس إديسون' },
  { q: 'الوقت الذي تستمتع بإضاعته ليس وقتاً ضائعاً، ولكن وقت المذاكرة لا يعوض.', by: 'بيرتراند راسل' },
  { q: 'ابدأ من حيث أنت. استخدم ما لديك. افعل ما تستطيع.', by: 'آرثر آش' },
  { q: 'اجتهد في الصمت، ودع النجاح يصنع الضجيج.', by: 'فرانك أوشن' },
  { q: 'العقل ليس وعاء يجب ملؤه، بل نار يجب إشعالها.', by: 'بلوتارخ' },
  { q: 'كل إنجاز عظيم يبدأ بقرار المحاولة.', by: 'جون كينيدي' },
  { q: 'الصبر مر، ولكن ثماره حلوة.', by: 'أرسطو' },
  { q: 'الفشل هو فرصة للبدء من جديد بذكاء أكبر.', by: 'هنري فورد' },
  { q: 'التعلم لا يرهق العقل أبداً.', by: 'ليوناردو دا فينشي' },
  { q: 'الجهد المتواصل، وليس القوة أو الذكاء، هو مفتاح إطلاق قدراتنا.', by: 'وينستون تشرشل' },
  { q: 'عليك أن تفعل الأشياء التي تعتقد أنك لا تستطيع فعلها.', by: 'إليانور روزفلت' },
  { q: 'الجذور الخاصة بالتعليم مريرة، لكن الثمرة حلوة.', by: 'أرسطو' },
  { q: 'لا تدع الأمس يستهلك الكثير من اليوم.', by: 'ويل روجرز' },
  { q: 'الشخص الذي لا يقرأ ليس لديه ميزة على الشخص الذي لا يستطيع القراءة.', by: 'مارك توين' },
  { q: 'الفرق بين الممكن والمستحيل يكمن في تصميم الشخص.', by: 'تومي لاسوردا' },
  { q: 'نحن ما نفعله مراراً وتكراراً. التميز إذن ليس فعلاً، بل عادة.', by: 'أرسطو' },
  { q: 'الأحلام لا تتحقق بالسحر، بل تحتاج إلى عرق، وتصميم، وعمل جاد.', by: 'كولن باول' },
  { q: 'في كل صعوبة تكمن فرصة.', by: 'ألبرت أينشتاين' },
  { q: 'الطريقة الأفضل للتنبؤ بالمستقبل هي اختراعه.', by: 'آلان كاي' },
  { q: 'كلما زادت قراءتك، زادت الأشياء التي ستعرفها.', by: 'دكتور سوس' },
  { q: 'قليل من التقدم كل يوم يضيف إلى نتائج كبيرة.', by: 'لاو تسو' },
  { q: 'من لم يذق مر التعلم ساعة، تجرع ذل الجهل طوال حياته.', by: 'الإمام الشافعي' },
  { q: 'التعليم جواز السفر إلى المستقبل.', by: 'مالكولم إكس' },
  { q: 'الرجل الحكيم سيبتكر فرصاً أكثر مما يجد.', by: 'فرانسيس بيكون' },
  { q: 'لا توجد طرق مختصرة لأي مكان يستحق الذهاب إليه.', by: 'بيفرلي سيلز' },
  { q: 'رحلة الألف ميل تبدأ بخطوة.', by: 'لاو تسو' },
  { q: 'المعرفة قوة.', by: 'فرانسيس بيكون' },
  { q: 'العمل الشاق يتغلب على الموهبة عندما لا تعمل الموهبة بجد.', by: 'تيم نوتكي' },
  { q: 'من جد وجد، ومن زرع حصد.', by: 'مثل عربي' },
  { q: 'العوائق هي تلك الأشياء المخيفة التي تراها عندما ترفع عينيك عن هدفك.', by: 'هنري فورد' },
  { q: 'اجعل من حياتك رسالة، لا مجرد قصة.', by: 'أوليفر هولمز' },
  { q: 'النجاح يولد من رحم الفشل.', by: 'رالف والدو إمرسون' },
  { q: 'العبقرية هي 1% إلهام و 99% عرق.', by: 'توماس إديسون' },
  { q: 'إذا كان بإمكانك تخيله، يمكنك تحقيقه.', by: 'والت ديزني' },
  { q: 'تذكر أن الفشل هو مجرد حدث، وليس شخصاً.', by: 'زيج زيجلار' },
  { q: 'النجاح هو المضي من فشل إلى فشل دون فقدان الحماس.', by: 'وينستون تشرشل' },
  { q: 'المستحيل كلمة موجودة فقط في قاموس الحمقى.', by: 'نابليون بونابرت' }
];

const GENERAL_QUOTES_EN = [
  { q: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', by: 'Winston Churchill' },
  { q: 'The only way to do great work is to love what you do.', by: 'Steve Jobs' },
  { q: 'Don\'t be afraid to give up the good to go for the great.', by: 'John D. Rockefeller' },
  { q: 'Education is the most powerful weapon which you can use to change the world.', by: 'Nelson Mandela' },
  { q: 'The secret of getting ahead is getting started.', by: 'Mark Twain' },
  { q: 'Believe you can and you\'re halfway there.', by: 'Theodore Roosevelt' },
  { q: 'Don\'t stop when you\'re tired. Stop when you\'re done.', by: 'Marilyn Monroe' },
  { q: 'Great things never come from comfort zones.', by: 'Neil Armstrong' },
  { q: 'Every expert was once a beginner.', by: 'Helen Hayes' },
  { q: 'The future depends on what you do today.', by: 'Mahatma Gandhi' },
  { q: 'It does not matter how slowly you go as long as you do not stop.', by: 'Confucius' },
  { q: 'An investment in knowledge pays the best interest.', by: 'Benjamin Franklin' },
  { q: 'A drop of water hollows out stone, not by force, but by falling often.', by: 'Lucretius' },
  { q: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', by: 'Thomas A. Edison' },
  { q: 'Time you enjoy wasting is not wasted time, but study time is irreplaceable.', by: 'Bertrand Russell' },
  { q: 'Start where you are. Use what you have. Do what you can.', by: 'Arthur Ashe' },
  { q: 'Work hard in silence, let your success be your noise.', by: 'Frank Ocean' },
  { q: 'The mind is not a vessel to be filled, but a fire to be kindled.', by: 'Plutarch' },
  { q: 'Every great achievement begins with the decision to try.', by: 'John F. Kennedy' },
  { q: 'Patience is bitter, but its fruit is sweet.', by: 'Aristotle' },
  { q: 'Failure is the opportunity to begin again more intelligently.', by: 'Henry Ford' },
  { q: 'Learning never exhausts the mind.', by: 'Leonardo da Vinci' },
  { q: 'Continuous effort, not strength or intelligence, is the key to unlocking our potential.', by: 'Winston Churchill' },
  { q: 'You must do the things you think you cannot do.', by: 'Eleanor Roosevelt' },
  { q: 'The roots of education are bitter, but the fruit is sweet.', by: 'Aristotle' },
  { q: 'Do not let yesterday take up too much of today.', by: 'Will Rogers' },
  { q: 'The man who does not read has no advantage over the man who cannot read.', by: 'Mark Twain' },
  { q: 'The difference between the impossible and the possible lies in a person\'s determination.', by: 'Tommy Lasorda' },
  { q: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', by: 'Aristotle' },
  { q: 'A dream doesn\'t become reality through magic; it takes sweat, determination and hard work.', by: 'Colin Powell' },
  { q: 'In the middle of every difficulty lies opportunity.', by: 'Albert Einstein' },
  { q: 'The best way to predict the future is to invent it.', by: 'Alan Kay' },
  { q: 'The more that you read, the more things you will know.', by: 'Dr. Seuss' },
  { q: 'A little progress each day adds up to big results.', by: 'Lao Tzu' },
  { q: 'Whoever does not taste the bitterness of learning for an hour, will swallow the humiliation of ignorance for a lifetime.', by: 'Imam Al-Shafi\\'i' },
  { q: 'Education is the passport to the future.', by: 'Malcolm X' },
  { q: 'A wise man will make more opportunities than he finds.', by: 'Francis Bacon' },
  { q: 'There are no shortcuts to any place worth going.', by: 'Beverly Sills' },
  { q: 'A journey of a thousand miles begins with a single step.', by: 'Lao Tzu' },
  { q: 'Knowledge is power.', by: 'Francis Bacon' },
  { q: 'Hard work beats talent when talent doesn\'t work hard.', by: 'Tim Notke' },
  { q: 'Whoever strives finds, and whoever sows reaps.', by: 'Arabic Proverb' },
  { q: 'Obstacles are those frightful things you see when you take your eyes off your goal.', by: 'Henry Ford' },
  { q: 'Make your life a mission - not an intermission.', by: 'Oliver Holmes' },
  { q: 'Success is born out of failure.', by: 'Ralph Waldo Emerson' },
  { q: 'Genius is 1% inspiration and 99% perspiration.', by: 'Thomas Edison' },
  { q: 'If you can dream it, you can do it.', by: 'Walt Disney' },
  { q: 'Remember that failure is an event, not a person.', by: 'Zig Ziglar' },
  { q: 'Success is going from failure to failure without losing your enthusiasm.', by: 'Winston Churchill' },
  { q: 'Impossible is a word to be found only in the dictionary of fools.', by: 'Napoleon Bonaparte' }
];
